export type ChannelModule = {
  id: string;
  name: string;
  shortName: string;
  category: string;
  color: string;
  bestFor: string;
  whenToUse: string;
  setupFields: string[];
  generatedOutputs: string[];
  creativeFormats: string[];
  publishingMethod: string;
  complianceNotes: string[];
  metricFields?: string[];
  integrationPath?: "api_ready" | "api_later" | "manual_assisted" | "internal_draft";
  availableInBuilder?: boolean;
  recommendedFor?: string[];
};

export const channelModules: ChannelModule[] = [
  {
    id: "google_business",
    name: "Google Business Profile",
    shortName: "GBP",
    category: "Local search",
    color: "#34A853",
    bestFor: "Free local visibility, Maps/search discovery, fresh arrivals, and local offer posts.",
    whenToUse: "Use for every marketable vehicle that has clean photos and dealership-safe finance language.",
    setupFields: ["Post type", "CTA link", "Offer expiration", "Local angle", "Photo choice"],
    generatedOutputs: ["Short local post", "CTA text", "Photo recommendation", "Publishing checklist"],
    creativeFormats: ["Square photo", "Vehicle photo", "Offer image"],
    publishingMethod: "Manual copy/export now; Google Business Profile API adapter later.",
    complianceNotes: ["Use concise local copy.", "Avoid unsupported financing guarantees.", "Keep offer language conditional when financing is mentioned."],
    metricFields: ["Views", "Clicks", "Calls", "Direction requests"],
    integrationPath: "api_later",
  },
  {
    id: "google_ads",
    name: "Google Ads Search",
    shortName: "G Ads",
    category: "Paid search",
    color: "#4285F4",
    bestFor: "High-intent local buyers searching for financing, used cars, BHPH, trucks, SUVs, or dealership terms.",
    whenToUse: "Use for approved paid campaigns where the owner signs off on budget and campaign direction.",
    setupFields: ["Campaign goal", "Budget", "Location radius", "Keyword theme", "Final URL", "Call asset"],
    generatedOutputs: ["Responsive search headlines", "Descriptions", "Keyword themes", "Negative keyword starters", "Launch checklist"],
    creativeFormats: ["No image required", "Landing page/vehicle URL"],
    publishingMethod: "Export campaign setup package now; Google Ads API adapter later.",
    complianceNotes: ["No guaranteed approval claims.", "No invented payments, APR, or terms.", "Use subject-to-approval language on finance-related landing pages."],
    metricFields: ["Spend", "Impressions", "Clicks", "Calls", "Conversions", "Cost per lead"],
    integrationPath: "api_later",
  },
  {
    id: "meta_paid",
    name: "Meta Paid Ads",
    shortName: "Meta",
    category: "Paid social",
    color: "#1877F2",
    bestFor: "Finance applications, calls, Messenger leads, and Spanish-language reach.",
    whenToUse: "Use when the lot wants predictable reach beyond free Facebook posts.",
    setupFields: ["Objective", "Budget", "Schedule", "Radius", "Language", "CTA", "Destination"],
    generatedOutputs: ["Primary text variants", "Headlines", "Descriptions", "Audience summary", "Launch checklist"],
    creativeFormats: ["Feed 1:1", "Feed 4:5", "Story/Reel 9:16"],
    publishingMethod: "Launch/export package now; Meta API later.",
    complianceNotes: ["Avoid guaranteed approval claims.", "Use subject-to-approval language for financing."],
    metricFields: ["Spend", "Reach", "Impressions", "Clicks", "Messages", "Leads", "Cost per lead"],
    integrationPath: "api_later",
  },
  {
    id: "instagram_organic",
    name: "Instagram Organic",
    shortName: "Instagram",
    category: "Organic social",
    color: "#E1306C",
    bestFor: "Visual inventory awareness and story/reel posts.",
    whenToUse: "Use when the vehicle has strong photos or a quick walkaround angle.",
    setupFields: ["Post type", "Caption tone", "CTA", "Hashtag set"],
    generatedOutputs: ["Caption", "Story overlay text", "Reel script", "Hashtags"],
    creativeFormats: ["Feed 1:1", "Feed 4:5", "Story/Reel 9:16"],
    publishingMethod: "Copy/export package.",
    complianceNotes: ["Keep text short and clear.", "Do not overcrowd story creatives."],
    metricFields: ["Reach", "Profile visits", "Link clicks", "Messages"],
    integrationPath: "manual_assisted",
  },
  {
    id: "craigslist",
    name: "Craigslist",
    shortName: "Craigslist",
    category: "Marketplace",
    color: "#5C3D7E",
    bestFor: "Low-cost local buyer demand.",
    whenToUse: "Use for affordable vehicles, aging inventory, and budget shoppers.",
    setupFields: ["Location", "Price", "Category", "Repost reminder"],
    generatedOutputs: ["Listing title", "Plain-text body", "Posting checklist"],
    creativeFormats: ["Photo set"],
    publishingMethod: "Manual export/checklist.",
    complianceNotes: ["Plain text works best.", "Do not overstate financing terms."],
    metricFields: ["Listing views", "Replies", "Calls", "Appointments"],
    integrationPath: "manual_assisted",
  },
  {
    id: "cars_com",
    name: "Cars.com Assisted Package",
    shortName: "Cars.com",
    category: "Marketplace",
    color: "#532380",
    bestFor: "Paid marketplace listings and buyers comparing inventory across dealers.",
    whenToUse: "Use when the dealer has Cars.com access or wants a clean listing package prepared for upload.",
    setupFields: ["Listing package type", "Feature emphasis", "Condition notes", "Photo order", "Seller notes"],
    generatedOutputs: ["Cars.com title", "Marketplace description", "Feature highlights", "Seller notes", "Upload checklist"],
    creativeFormats: ["Photo set", "Primary image", "Optional square promo"],
    publishingMethod: "Manual assisted package; API/feed access later if permissioned.",
    complianceNotes: ["Keep descriptions factual.", "Avoid unsupported condition claims.", "Do not invent warranty, certification, or financing terms."],
    metricFields: ["Views", "Leads", "Calls", "Messages", "Appointments"],
    integrationPath: "manual_assisted",
  },
  {
    id: "autotrader",
    name: "AutoTrader Assisted Package",
    shortName: "AutoTrader",
    category: "Marketplace",
    color: "#D71920",
    bestFor: "Higher-intent shoppers researching specific used vehicles and dealership inventory.",
    whenToUse: "Use when the dealer has AutoTrader access or wants a stronger marketplace listing package.",
    setupFields: ["Listing package type", "Feature emphasis", "Condition notes", "Photo order", "Price/down-payment policy"],
    generatedOutputs: ["AutoTrader title", "Description", "Feature bullets", "Seller notes", "Upload checklist"],
    creativeFormats: ["Photo set", "Primary image"],
    publishingMethod: "Manual assisted package; API/feed access later if permissioned.",
    complianceNotes: ["Keep claims factual.", "Avoid unsupported warranty/certified language.", "Do not invent payments or approval promises."],
    metricFields: ["Views", "Leads", "Calls", "Messages", "Appointments"],
    integrationPath: "manual_assisted",
  },
  {
    id: "short_video",
    name: "TikTok / YouTube Shorts",
    shortName: "Short Video",
    category: "Video",
    color: "#111827",
    bestFor: "Walkarounds, quick feature highlights, Spanish promos, and future Google Omni-ready storyboards.",
    whenToUse: "Use when a vehicle has enough photos/video potential for vertical short-form content.",
    setupFields: ["Video type", "Duration", "Angle", "Language", "Shot count"],
    generatedOutputs: ["Walkaround script", "Shot list", "Caption", "Thumbnail/title ideas", "Storyboard seed"],
    creativeFormats: ["Vertical 9:16", "Thumbnail"],
    publishingMethod: "Script/storyboard/export now; Google Omni adapter later.",
    complianceNotes: ["Show actual vehicle condition.", "Avoid misleading urgency.", "Do not imply financing approval is guaranteed."],
    metricFields: ["Views", "Watch time", "Profile visits", "Clicks", "Messages"],
    integrationPath: "manual_assisted",
  },
  {
    id: "facebook_organic",
    name: "Facebook Organic / Groups",
    shortName: "FB Organic",
    category: "Organic social",
    color: "#2563EB",
    bestFor: "Existing CarsForSale/MyCommandCenter group-post workflow and quick bilingual outreach.",
    whenToUse: "Use later when GetGoGone needs to support, package, or audit the current in-lot Facebook posting process.",
    setupFields: ["Posting angle", "Language", "Group checklist", "Repost reminder"],
    generatedOutputs: ["Group post copy", "Short title", "Spanish version", "Reply starters"],
    creativeFormats: ["Square image", "Vehicle photo set"],
    publishingMethod: "Copy/export/checklist; current lot workflow remains CarsForSale/MyCommandCenter.",
    complianceNotes: ["Keep payment/down-payment language conditional.", "Respect group rules."],
    metricFields: ["Group posts", "Replies", "Messages", "Calls"],
    integrationPath: "manual_assisted",
  },
  {
    id: "linkedin_commercial",
    name: "LinkedIn Commercial Vehicles",
    shortName: "LinkedIn",
    category: "Professional",
    color: "#0A66C2",
    bestFor: "Work trucks, cargo vans, passenger vans, fleet and business-use vehicles.",
    whenToUse: "Use only when the vehicle has a clear business/work use case and the dealership has a company page.",
    setupFields: ["Business audience", "Use case", "Company page vs paid", "CTA"],
    generatedOutputs: ["Professional post copy", "Commercial use bullets", "Business headline"],
    creativeFormats: ["Feed image", "Document/flyer"],
    publishingMethod: "Copy/export or paid campaign package.",
    complianceNotes: ["Lead with utility and ROI, not consumer hype."],
    metricFields: ["Impressions", "Clicks", "Profile visits", "Leads"],
    integrationPath: "manual_assisted",
    recommendedFor: ["truck", "van"],
  },
  {
    id: "sms_email",
    name: "SMS / Email",
    shortName: "Direct",
    category: "Direct marketing",
    color: "#0891B2",
    bestFor: "Existing leads, past buyers, and segmented follow-up.",
    whenToUse: "Use for targeted audiences with consent and clear follow-up value.",
    setupFields: ["Segment", "Channel", "Schedule", "Language", "Consent reminder"],
    generatedOutputs: ["SMS copy", "Email subject/body", "Follow-up variants"],
    creativeFormats: ["None", "Email header optional"],
    publishingMethod: "Draft/save now; provider integration later.",
    complianceNotes: ["Respect opt-out/consent rules.", "Keep SMS short and personal."],
    metricFields: ["Recipients", "Replies", "Clicks", "Appointments"],
    integrationPath: "internal_draft",
  },
  {
    id: "marketplace_listings",
    name: "Marketplace Legacy Bundle",
    shortName: "Marketplaces",
    category: "Marketplace",
    color: "#1F8245",
    bestFor: "Legacy saved campaigns that used the old combined marketplace module.",
    whenToUse: "Do not use for new packages unless a generic marketplace export is needed.",
    setupFields: ["Marketplace", "Listing emphasis", "Condition notes", "Feature highlights"],
    generatedOutputs: ["Listing title", "Marketplace description", "Feature highlights", "Seller notes"],
    creativeFormats: ["Photo set"],
    publishingMethod: "Legacy export/checklist. Prefer Cars.com or AutoTrader modules for new work.",
    complianceNotes: ["Keep descriptions factual.", "Avoid unsupported condition claims."],
    metricFields: ["Views", "Leads", "Calls"],
    integrationPath: "manual_assisted",
    availableInBuilder: false,
  },
];

export const activeChannelModules = channelModules.filter(module => module.availableInBuilder !== false);
